name: OpenAPI Diff & PR Comment

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  openapi-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r cc-webapp/backend/requirements.txt
          pip install pytest requests

      - name: Backup baseline before export
        run: |
          mkdir -p artifacts
          if [ -f cc-webapp/backend/current_openapi.json ]; then cp cc-webapp/backend/current_openapi.json artifacts/openapi_baseline.json; else echo '{}' > artifacts/openapi_baseline.json; fi

      - name: Export OpenAPI (FastAPI app)
        working-directory: cc-webapp/backend/app
        env:
          PYTHONPATH: ../
        run: |
          python -m app.export_openapi

      - name: Create textual diff
        shell: python
        run: |
          import difflib, pathlib
          before = pathlib.Path('artifacts/openapi_baseline.json').read_text(encoding='utf-8')
          after = pathlib.Path('cc-webapp/backend/current_openapi.json').read_text(encoding='utf-8')
          diff = difflib.unified_diff(before.splitlines(True), after.splitlines(True), fromfile='baseline', tofile='current')
          pathlib.Path('artifacts/openapi.diff.txt').write_text(''.join(diff), encoding='utf-8')

      - name: Run OpenAPI contract test
        working-directory: cc-webapp/backend
        env:
          PYTHONPATH: .
        run: |
          pytest -q tests -k openapi_diff_ci --maxfail=1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi-diff
          path: |
            artifacts/openapi_baseline.json
            cc-webapp/backend/current_openapi.json
            artifacts/openapi.diff.txt

      - name: Comment on PR with summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            function read(p){ try { return fs.readFileSync(p, 'utf8'); } catch { return ''; } }
            const baseline = read('artifacts/openapi_baseline.json');
            const current = read('cc-webapp/backend/current_openapi.json');
            const diff = read('artifacts/openapi.diff.txt');
            const body = `### OpenAPI Diff Report\n\n- Baseline size: ${baseline.length} bytes\n- Current size: ${current.length} bytes\n\n<details><summary>Unified Diff</summary>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n` +
              "\n\n```diff\n" + diff.substring(0, 60000) + "\n```\n\n" +
              `</details>`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
